name: CI

on: push

jobs:
  run-linters:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Example
        run: npm run build-example-no-webpack

      - name: Build Webpack
        run: npm run build-example

      - name: Test
        run: npm run serve-example

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name : Run test
        run: npm run prepublishOnly
